sudo: false
language: php

matrix:
  fast_finish: true
  include:
  - php: 5.5
    env:
    - REPORT_COVERAGE=true
  - php: 5.6
  - php: 7
  - php: hhvm
  allow_failures:
  - php: hhvm

cache:
  directories:
  - $HOME/.composer/cache
  - vendor

before_install:
  - if [[ $REPORT_COVERAGE != 'true' && $TRAVIS_PHP_VERSION != "hhvm"  ]]; then phpenv config-rm xdebug.ini ; fi
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction

script:
  - composer test

after_script:
  - if [[ $REPORT_COVERAGE == 'true' ]]; then composer coverage ; fi
