language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
  - phpunit

after_script:
  - php vendor/bin/coveralls -v
